#!/usr/bin/env python3
"""Portable local commands; dotenv is parsed as data and is never executed by a shell."""
from __future__ import annotations
import argparse
import os
from pathlib import Path
import re
import secrets
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]


def read_env(path: Path) -> dict[str, str]:
    values = {}
    if not path.exists():
        return values
    for n, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        key, sep, value = line.partition("=")
        if not sep or not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", key.strip()):
            raise ValueError(f"Invalid environment entry on line {n}")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        values[key.strip()] = value
    return values


def initialize(path: Path, profile: str = "demo") -> None:
    values = read_env(ROOT / ".env.example") | read_env(path)
    values["SPRING_PROFILES_ACTIVE"] = profile
    values["APP_SECURITY_EMAIL_DEV_MODE"] = "true" if profile == "demo" else "false"
    for key in ("DIFY_ENABLED", "DIFY_BASE_URL", "DIFY_API_KEY"):
        values.pop(key, None)
    for key in ("APP_SECURITY_TOKEN_SECRET", "APP_SECURITY_EMAIL_SECRET", "SUPPORT_AGENT_TOKEN"):
        current = values.get(key, "")
        if len(current) < 32 or any(marker in current.lower() for marker in ("replace-with", "development", "change-me", "example")):
            values[key] = secrets.token_hex(32)
    if profile == "prod":
        for key in ("DB_PASSWORD", "MYSQL_ROOT_PASSWORD", "APP_ADMIN_PASSWORD"):
            if not values.get(key) or values[key] in {"campus_pulse_123", "local-root-demo-password"}:
                values[key] = secrets.token_hex(24)
    # Single quotes prevent Compose from interpolating $, backticks or spaces.
    if any("'" in value or "\n" in value or "\r" in value for value in values.values()):
        raise ValueError("Use dotenv values without single quotes or line breaks")
    temp = path.with_suffix(".tmp")
    with os.fdopen(os.open(temp, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600), "w") as f:
        f.write("# Local configuration; generated by tools/dev.py. Never commit this file.\n")
        f.writelines(f"{key}='{value}'\n" for key, value in values.items())
    temp.replace(path)
    print(f"Configured {profile} in {path}; secret values were not printed.")


def environment(path: Path) -> dict[str, str]:
    env = read_env(path)
    env.update(os.environ)
    # Java 17 uses the process locale for native paths, including Chinese checkout names.
    if env.get("LC_ALL", "C") in {"C", "POSIX", ""}:
        env["LC_ALL"] = "en_US.UTF-8" if sys.platform == "darwin" else "C.UTF-8"
    env.setdefault("LANG", env["LC_ALL"])
    env.setdefault("SERVER_PORT",env.get("BACKEND_PORT","8080"))
    env.setdefault("PORT",env.get("FRONTEND_PORT","8125"))
    env.setdefault("TARGET","http://127.0.0.1:"+env.get("BACKEND_PORT","8080"))
    env.setdefault("DB_URL", "jdbc:mysql://127.0.0.1:" + env.get("MYSQL_PORT", "3306") + "/" + env.get("MYSQL_DATABASE", "campus_pulse") + "?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true")
    for key, source, default in (("CAMPUS_DB_HOST", "", "127.0.0.1"), ("CAMPUS_DB_PORT", "MYSQL_PORT", "3306"),
                                 ("CAMPUS_DB_USER", "DB_USERNAME", "campus_pulse"), ("CAMPUS_DB_PASSWORD", "DB_PASSWORD", "campus_pulse_123"),
                                 ("CAMPUS_DB_NAME", "MYSQL_DATABASE", "campus_pulse")):
        env.setdefault(key, env.get(source, default))
    if sys.platform == "darwin" and not env.get("JAVA_HOME"):
        java = subprocess.run(["/usr/libexec/java_home", "-v", "17"], capture_output=True, text=True)
        if java.returncode == 0:
            env["JAVA_HOME"] = java.stdout.strip()
    return env


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--env-file", type=Path, default=ROOT / ".env")
    sub = parser.add_subparsers(dest="action", required=True)
    init = sub.add_parser("init"); init.add_argument("--profile", choices=("demo", "prod"), default="demo")
    for action in ("up", "down", "backend", "frontend", "test"):
        sub.add_parser(action)
    run = sub.add_parser("run"); run.add_argument("command", nargs=argparse.REMAINDER)
    args = parser.parse_args()
    if args.action == "init":
        initialize(args.env_file, args.profile); return
    if not args.env_file.exists() and args.action == "up":
        initialize(args.env_file)
    env = environment(args.env_file)
    compose = ["docker", "compose", "--env-file", str(args.env_file)] if args.env_file.exists() else ["docker", "compose"]
    commands = {
        "up": compose + ["up", "--build", "-d", "--wait", "--wait-timeout", "240"],
        "down": compose + ["down"],
        "backend": ["mvn", "-f", "backend/pom.xml", "spring-boot:run"],
        "frontend": ["node", "tools/local_http_proxy.cjs"],
        "test": ["mvn", "-f", "backend/pom.xml", "verify"],
        "run": getattr(args, "command", []),
    }
    command = commands[args.action]
    if command and command[0] == "--": command = command[1:]
    if not command: parser.error("Provide a command after run")
    if not shutil.which(command[0]): parser.error(f"Required executable not installed: {command[0]}")
    raise SystemExit(subprocess.call(command, cwd=ROOT, env=env))

if __name__ == "__main__":
    main()
